version: "3"
services:
  ember:
    image: danlynn/ember-cli:3.1.4-node_10.1
    environment:
      CI: "true"
    command: "ember server --environment production --proxy=http://127.0.0.1:8000"
    volumes:
      - .:/myapp
    ports:
       - "4200:4200"
       - "7020:7020"
       - "5779:5779"
